### ISSUE TITLE
[1.12.2] Animaion for pam's wee flowers is bugged

### ISSUE THREAD

**Issue by Federsavo** [BrisingrAerowing/ClochePlusPlus#1]
![2020-09-21_19 23 26](https://user-images.githubusercontent.com/29519894/93799900-180f8c00-fc40-11ea-8955-7ce8d624e636.png)

Tested in a creative world with just:

Forge 14.23.5.2854
clocheplusplus 0.6
Jei 4.16.1.301
Weee! Flowers 1.12.2b

**Comment by brisingraerowing** [comment]
I've seen this, but I have no idea what causes it. I copied the code directly from IE.

**Comment by brisingraerowing** [comment]
I managed to fix the bug. A new version will be uploaded soon.

**Comment by brisingraerowing** [comment]
The new file has been uploaded and hopefully should be available soon.

**Comment by Federsavo** [comment]
Nice! it works on my end too.

Thanks for the superfast update.

**Comment by brisingraerowing** [comment]
That's good.
